# Generated by Django 3.2.5 on 2021-08-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('fone', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=254)),
                ('dtcadastro', models.DateTimeField(auto_now_add=True, db_column='dtCadastro')),
                ('dtatualizacao', models.DateTimeField(auto_now=True, db_column='dtAtualizacao', null=True)),
            ],
            options={
                'db_table': 'lead',
            },
        ),
    ]
